dossier Docs
139bercy/cloud-appliance-observability pull request #17
Opened 2020-01-17 14:09 UTC by bgaschet

Ajout du dossier Docs avec la présentation de l'appliance et des schémas

2020-01-20 15:19 UTC, mgrzybek requested changes
Quelques contresens et des erreurs de mise en page.

2020-01-20 15:19 UTC, mgrzybek commented on Docs/Presentation.md
> +L'appliance est un outillage de sauvegarde et de restauration de Graylog vers un service de stockage objet Swift en environnement Openstack.
Non, ne pas confondre avec `graylog-recovery`.
C'est une appliance de contralisation et d'exploitation de logs utilisant l'outil `Graylog`.

2020-01-20 15:19 UTC, mgrzybek commented on Docs/Presentation.md
> +- L'envoi de la donnée vers l'appliance;
Quelle est la différence entre "vers l'outil" et "vers l'appliance" ?

2020-01-20 15:19 UTC, mgrzybek commented on Docs/Presentation.md
> +La stack HEAT contient des machines de projet qui envoie des logs vers l’appliance.
La stack HEAT ne contient pas de machines du projet.  Elle contient juste l'appliance.

2020-01-20 15:19 UTC, mgrzybek commented on Docs/Presentation.md
> +Graylog est un service publié aux utilisateurs contrairement aux services internes qui ne sont pas atteignable par les utilisateurs
atteignable**s**

2020-01-20 15:19 UTC, mgrzybek commented on Docs/Presentation.md
> +Des données sont envoyés par l'API, l'interface Homme/Machine et différents types de messages vers l'appliance et plus précisement vers graylog pour traitement.
> Des **messages** sont envoyé**e**s par **l'API REST** et différents types de **protocoles** vers l'appliance. Ces services sont rendus par `Graylog`.

2020-01-20 15:19 UTC, mgrzybek commented on Docs/Presentation.md
> +- ELS stocke les messages
Les conteneurs stockent leurs fichiers dans des volumes `Cinder` séparés.
Cinder == Disques séparés.

2020-01-20 15:19 UTC, mgrzybek commented on Docs/Presentation.md
> +## L'envoi de la donnée vers l'outils
Pas de "s" à "outils".
Donnée au pluriel.

2020-01-20 15:19 UTC, mgrzybek commented on Docs/Presentation.md
> +Cron est un outils qui permet de faire des taches planifiés. Ici, il s’occupe de lancer graylog-recovery régulièrement
Pas de "s" à "outils".

2020-01-20 15:19 UTC, mgrzybek commented on Docs/Presentation.md
> +L’application est alors installé dans un conteneur. Une sortie console vers des moteurs de conteneurs permet l’envoi vers l’appliance Graylog.
Mise en page pas très propre.

2020-01-20 15:19 UTC, mgrzybek commented on FORK
> +test fork..
À enlever de la PR.

2020-01-20 15:19 UTC, mgrzybek commented on Docs/sauvegarde-restauration
> +<mxfile host="Electron" modified="2020-01-15T14:52:50.663Z" agent="Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) draw.io/12.2.2 Chrome/78.0.3904.94 Electron/7.1.0 Safari/537.
Parenthèses à "webservices" pas nécessaires.

2020-01-20 15:19 UTC, mgrzybek commented on Docs/instance-applicative
> +<mxfile host="Electron" modified="2020-01-16T10:09:55.565Z" agent="Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) draw.io/12.2.2 Chrome/78.0.3904.94 Electron/7.1.0 Safari/537.
* C'est Springb**oo**t
* Manque des majuscules

2020-01-20 15:19 UTC, mgrzybek commented on Docs/Schema-blocs-fonctionnels
> +<mxfile host="Electron" modified="2020-01-17T09:47:51.160Z" agent="Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) draw.io/12.2.2 Chrome/78.0.3904.94 Electron/7.1.0 Safari/537.
Les machines du projet ne font pas partie de la stack HEAT.

2020-01-21 10:29 UTC, bgaschet commented
Modifications suite aux remarques de Mathieu

2020-01-21 16:04 UTC, mgrzybek approved these changes

2020-01-21 16:04 UTC, merged